[package]
name = "aoc_6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="aoc_6"
path="src/main.rs"

[lib]
name="aoc_6"
path="src/lib.rs"

[dependencies]
