[package]
name = "aoc_11"
version = "0.1.0"
edition = "2021"

[lib]
name="aoc_11"
path="src/lib.rs"

[[bin]]
name="aoc_11"
path="src/main.rs"


[dependencies]
regex = "1"
lazy_static = "1"
itertools.workspace = true