[package]
name = "aoc_8"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc_8"
path = "src/main.rs"

[lib]
name = "aoc_8"
path = "src/lib.rs"

[dependencies]
take-until = "0.1.0" # Needed, waiting for https://github.com/rust-lang/rust/issues/62208